version: '3'
services:
  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    container_name: mongo
    volumes:
      - './dockervolume/mongodb:/data/db'