// lobby with players
export const lobbyPhase = {
  slug: "TEST-SLUG-LOBBYPHASE",
  host: "JACTON",
  createdAt: 1588553102804,
  updateAt: 1588553102804,
  players: [
    "JACTON",
    "CHEDGO",
    "ANDY",
    "ANYA",
    "JAMES",
    "BIG DADDY DERS",
    "BRO-SAUCE",
  ],
  settings: {
    rotations: 2,
    turnDurationSeconds: 90,
    teamsCount: 2,
  },
  games: [],
  prompts: [],
};

// prompt writing phase w/ prompts
export const promptPhase = {
  slug: "TEST-SLUG-PROMPTPHASE",
  host: "JACTON",
  createdAt: 1588553102804,
  updateAt: 1588553102804,
  players: [
    "JACTON",
    "CHEDGO",
    "ANDY",
    "ANYA",
    "JAMES",
    "BIG DADDY DERS",
    "BRO-SAUCE",
  ],
  settings: {
    rotations: 1,
    turnDurationSeconds: 90,
    teamsCount: 2,
  },
  games: [
    {
      startTime: 1588553102804,
      endTime: 1588553102804,
      teams: [
        {
          teamName: "TEAM A",
          teamPlayers: ["JACTON", "CHEDGO", "ANDY", "ANYA"],
          playerIndex: 0,
          score: 0,
        },
        {
          teamName: "TEAM B",
          teamPlayers: ["JAMES", "BIG DADDY DERS", "BRO-SAUCE"],
          playerIndex: 0,
          score: 0,
        },
      ],
      totalTurns: 16,
      turns: [],
    },
  ],
  prompts: [
    { author: "JACTON", prompt: "Taming of the Shrew" },
    { author: "JACTON", prompt: "Turn" },
    { author: "CHEDGO", prompt: "Othello" },
    { author: "CHEDGO", prompt: "Star Wars" },
    { author: "ANDY", prompt: "Once Upon a Time in Hollywood" },
    { author: "ANDY", prompt: "Raging" },
    { author: "ANYA", prompt: "The Stranger" },
    { author: "ANYA", prompt: "Kill Bill" },
    { author: "JAMES", prompt: "Inglorious Basterds" },
    { author: "JAMES", prompt: "Do the Right Thing" },
    { author: "BIG DADDY DERS", prompt: "Resevoir Dogs" },
    { author: "BIG DADDY DERS", prompt: "Resevoir Dogs 2" },
  ],
};

// mid game
export const midGamePhase = {
  slug: "TEST-SLUG-MIDGAMEPHASE",
  host: "BOBANYA",
  createdAt: 1588553102804,
  updatedAt: 1588553102804,
  players: ["BOBANYA", "GENJI", "MILLIE", "JILLY", "ROSA", "HEINRICH"],
  settings: {
    rotations: 2,
    turnDurationSeconds: 90,
    teamsCount: 2,
  },
  games: [
    {
      startTime: 1588553102804,
      endTime: null,
      teams: [
        {
          teamName: "BOOTY SHAKERS",
          teamPlayers: ["JILLY", "ROSA", "HEINRICH"],
          playerIndex: 2,
          score: 2,
        },
        {
          teamName: "SILVER TIGER CLAW",
          teamPlayers: ["BOBANYA", "GENJI", "MILLIE"],
          playerIndex: 2,
          score: 1,
        },
      ],
      totalTurns: 12,
      turns: [
        {
          startTime: 1588553102804,
          endTime: 1588554102804,
          teamIndex: 0,
          player: "JILLY",
          author: "BOBANYA",
          prompt: "car jacking",
          success: true,
        },
        {
          startTime: 1588555102804,
          endTime: 1588556102804,
          teamIndex: 1,
          player: "BOBANYA",
          author: "JILLY",
          prompt: "aquaphor",
          success: true,
        },
        {
          startTime: 1588557102804,
          endTime: 1588558102804,
          teamIndex: 0,
          player: "ROSA",
          author: "GENJI",
          prompt: "snail eating a cucumber",
          success: true,
        },
        {
          startTime: 1588558102804,
          endTime: 1588559102804,
          teamIndex: 1,
          player: "GENJI",
          author: "ROSA",
          prompt: "five star wings",
          success: false,
        },
        {
          startTime: 1588558102804,
          endTime: null,
          teamIndex: 0,
          player: "HEINRICH",
          author: "MILLIE",
          prompt: "i'm a lil bitch",
        },
      ],
    },
  ],
  prompts: [
    {
      author: "BOBANYA",
      prompt: "lip light",
    },
    {
      author: "GENJI",
      prompt: "star wards: the last jedi",
    },
    {
      author: "MILLIE",
      prompt: "plush baby legs",
    },
    {
      author: "JILLY",
      prompt: "smoking is cool kids",
    },
    {
      author: "ROSA",
      prompt: "smoothie hoochie",
    },
    {
      author: "HEINRICH",
      prompt: "gloop gloop gloop",
    },
    {
      author: "HEINRICH",
      prompt: "mousie go bye bye",
    },
  ],
};

// one turn left in game
export const endGamePhase = {
  slug: "TEST-SLUG-ENDGAMEPHASE",
  host: "CATCHI",
  createdAt: 1588553102804,
  updatedAt: 1588553102804,
  players: [
    "CATCHI",
    "CHEDGO",
    "MARCEL",
    "WATERMELON JIM",
    "UNDEAD STALIN",
    "BARBUNIA",
    "MALLARD FILMORE",
  ],
  settings: {
    rotations: 2,
    turnDurationSeconds: 90,
    teamsCount: 2,
  },
  games: [
    {
      startTime: 1588553102804,
      endTime: null,
      teams: [
        {
          teamName: "FLYING FUCKS",
          players: ["CATCHI", "MARCEL", "UNDEAD STALIN", "MALLARD FILMORE"],
          playerIndex: 3,
          score: 3,
        },
        {
          teamName: "CORPORATE SHILLS",
          players: ["CHEDGO", "WATERMELON JIM", "BARBUNIA"],
          playerIndex: 1,
          score: 5,
        },
      ],
      totalTurns: 16,
      turns: [
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "CATCHI",
          prompt: "jeremy bearimy",
          teamIndex: 1,
          player: "CHEDGO",
          success: false,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "CHEDGO",
          prompt: "corn dog bread",
          teamIndex: 0,
          player: "CATCHI",
          success: false,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "CATCHI",
          prompt: "banana pentagram",
          teamIndex: 1,
          player: "WATERMELON JIM",
          success: true,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "BARBUNIA",
          prompt: "cream of wheat",
          teamIndex: 0,
          player: "MARCEL",
          success: true,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "MARCEL",
          prompt: "balding eagle",
          teamIndex: 1,
          player: "BARBUNIA",
          success: true,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "CHEDGO",
          prompt: "orange you glad yer dead",
          teamIndex: 0,
          player: "UNDEAD STALIN",
          success: false,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "MARCEL",
          prompt: "deflowering cactus",
          teamIndex: 1,
          player: "CHEDGO",
          success: true,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "WATERMELON JIM",
          prompt: "imaginary number",
          teamIndex: 0,
          player: "MALLARD FILMORE",
          success: true,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "UNDEAD STALIN",
          prompt: "laserdisk copy of terminator",
          teamIndex: 1,
          player: "WATERMELON JIM",
          success: true,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "BARBUNIA",
          prompt: "self check-out",
          teamIndex: 0,
          player: "CATCHI",
          success: false,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "MALLARD FILMORE",
          prompt: "moby dick tracy",
          teamIndex: 1,
          player: "BARBUNIA",
          success: false,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "WATERMELON JIM",
          prompt: "horchata latte",
          teamIndex: 0,
          player: "MARCEL",
          success: true,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "UNDEAD STALIN",
          prompt: "perestroika",
          teamIndex: 1,
          player: "CHEDGO",
          success: true,
        },
      ],
    },
  ],
  prompts: [
    {
      author: "MALLARD FILMORE",
      prompt: "typewriter animation in powerpoint",
    },
  ],
};

// post-game lobby
export const postGamePhase = {
  slug: "TEST-SLUG-POSTGAMEPHASE",
  host: "CATCHI",
  createdAt: 1588553102804,
  updatedAt: 1588553102804,
  players: [
    "CATCHI",
    "CHEDGO",
    "MARCEL",
    "WATERMELON JIM",
    "UNDEAD STALIN",
    "BARBUNIA",
    "MALLARD FILMORE",
  ],
  settings: {
    rotations: 2,
    turnDurationSeconds: 90,
    teamsCount: 2,
  },
  games: [
    {
      startTime: 1588553102804,
      endTime: 1588553102804,
      teams: [
        {
          teamName: "FLYING FUCKS",
          players: ["CATCHI", "MARCEL", "UNDEAD STALIN", "MALLARD FILMORE"],
          playerIndex: 3,
          score: 3,
        },
        {
          teamName: "CORPORATE SHILLS",
          players: ["CHEDGO", "WATERMELON JIM", "BARBUNIA"],
          playerIndex: 1,
          score: 5,
        },
      ],
      totalTurns: 16,
      turns: [
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "CATCHI",
          prompt: "jeremy bearimy",
          teamIndex: 1,
          player: "CHEDGO",
          success: false,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "CHEDGO",
          prompt: "corn dog bread",
          teamIndex: 0,
          player: "CATCHI",
          success: false,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "CATCHI",
          prompt: "banana pentagram",
          teamIndex: 1,
          player: "WATERMELON JIM",
          success: true,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "BARBUNIA",
          prompt: "cream of wheat",
          teamIndex: 0,
          player: "MARCEL",
          success: true,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "MARCEL",
          prompt: "balding eagle",
          teamIndex: 1,
          player: "BARBUNIA",
          success: true,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "chedgo",
          prompt: "orange you glad yer dead",
          teamIndex: 0,
          player: "UNDEAD STALIN",
          success: false,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "MARCEL",
          prompt: "deflowering cactus",
          teamIndex: 1,
          player: "chedgo",
          success: true,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "WATERMELON JIM",
          prompt: "imaginary number",
          teamIndex: 0,
          player: "MALLARD FILMORE",
          success: true,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "UNDEAD STALIN",
          prompt: "laserdisk copy of terminator",
          teamIndex: 1,
          player: "WATERMELON JIM",
          success: true,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "BARBUNIA",
          prompt: "self check-out",
          teamIndex: 0,
          player: "CATCHI",
          success: false,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "MALLARD FILMORE",
          prompt: "moby dick tracy",
          teamIndex: 1,
          player: "BARBUNIA",
          success: false,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "WATERMELON JIM",
          prompt: "horchata latte",
          teamIndex: 0,
          player: "MARCEL",
          success: true,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "UNDEAD STALIN",
          prompt: "perestroika",
          teamIndex: 1,
          player: "chedgo",
          success: true,
        },
        {
          startTime: 1588553102804,
          endTime: 1588553102804,
          author: "MALLARD FILMORE",
          prompt: "typewriter animation in powerpoint",
          teamIndex: 0,
          player: "UNDEAD STALIN",
          success: true,
        },
      ],
    },
  ],
  prompts: [],
};
