name: Continuous Deployment

on:
  push:
    branches:
      - release

jobs:
  deploy:
    name: Deploy Client
    runs-on: ubuntu-latest

    env:
      SOURCE_DIR: "client/build/"
      AWS_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm run install:client

      - name: Build production
        if: github.ref == 'refs/heads/master'
        run: npm run build:client

        # Deploy part
      - name: Deploy production
        if: github.ref == 'refs/heads/master'
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: charades.space

  build:
    name: Deploy Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.1.6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "esc-charades"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "server"
