name: unit tests
on: [push]

jobs:
  build:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: npm install and run jest tests
        run: |
          cd server && npm install && npm run test-ci
